### ISSUE TITLE
Guide Button not working

### ISSUE THREAD

**Issue by ghost** [briankendall/xboxToVJoy#1]
Hi, first of all thank you very much, this is something great you are doing.

I can't make the Guide button to work as button 11 (the other buttons/axis works fine), i wonder if is because it needs a specific driver version or something like that, i'm using the wireless receiver driver from here: 
http://www.microsoft.com/hardware/en-gb/d/xbox-360-wireless-controller-for-windows

Button 11 works fine when i press "Guide" on the "xboxToVJoy Controller Window"

I also tried with the battery assistant open and closed (XBoxStat.exe), no luck.

I also would like to know which specific version of vJoy you have installed, because i tried vJoy_205_080115 and does not work, the app just say that "xboxToVJoy failed to start", i tried a old version i had before and it worked.

I'm on windows 8.1 x64.

Cheers.

**Comment by briankendall** [comment]
I do believe I'm running vJoy_204_080714. It's possible that later versions of vJoy are not compatible with the version of the SDK I'm running. (Although I certainly hope there isn't an incompatibility between versions 2.0.4 and 2.0.5!) When the "xboxToVJoy failed to start" error box appears, there should be some more text displayed. If you get that error again, can you let me know what the additional text is?

As for the guide button not working, I'm not sure what's going wrong. You're using the same Xbox 360 driver as me, so I don't think that has to do with it. Does the guide button work in any other applications or games? (For example, if you're running Steam, holding down the guide button will usually open it, or start Big Picture mode.)

**Comment by ghost** [comment]
Hi

vJoy_205_080115 says:

xboxTovJoy failed to start
One or more vJoy Devices could not be correlated with their DirectInput counterpart.

 vJoy_204_I080714 was also my old version that worked. Looks like vJoy_204_241214 is the latest working because the sdk changed on 2015-01

The guide button works fine on steam and on PPSSPP, etc., damn, that's pretty much what i wanted to recover, i had the japanese x360 drivers (dinput), but i changed to official drivers because i had some trouble with x360ce and i already started to miss the usable guide button.

PPSSPP:
https://github.com/hrydgard/ppsspp/blob/master/Windows/XinputDevice.cpp

Cheers.

**Comment by briankendall** [comment]
aireca, I'm going to try to see if I can fix this for you. Could you try doing the following:
1. Start xboxToVJoy with your 360 Controller connected.
2. Type Win+R
3. Enter "joy.cpl" without the quotes into the Run dialog that opens and press enter
4. In the dialog that opens, you should see your wireless 360 controller plus your vJoy devices listed. Double click the first vJoy device
5. It should open a window displaying the axes and buttons for that vJoy controller. Try pressing the Guide button and see if one of the red button icons lights up. Try pressing some of the other buttons too -- all of them should get a reaction.
6. If that vJoy device doesn't work, try the second vJoy device and so on until you've either tried them all or figured out which one is reacting to your button presses.

Let me know the results of that. It should give me a clue as to what's going wrong. Also, can you tell me whether the 360 controller is listed before or after the vJoy devices?

As for not working with the latest version of vJoy, at some point soon I'll try updating and fixing the software to work with it. For the time being just keep using vJoy 2.0.4.

**Comment by ghost** [comment]
That is actually what i was doing to check, the button 11 does not light up and the other buttons/axis works fine, Joy 1 is the real controller, Joy 2 is VJoy.

I tried with a different computer with different hardware and windows 7 x64 including a wired usb 360 controller this time and is the same, the guide button is the only one not working.

I also tried with UAC enabled and disabled, no luck.

Maybe your personal version is newer than the one that is uploaded.

**Comment by briankendall** [comment]
xboxToVJoy definitely always included guide button support, so it's not a version mismatch. Frankly though I have no idea why it's not working for you. I do run a dev version on my computer at home, so maybe that has something to do with it. I'll keep investigating and report back.

**Comment by briankendall** [comment]
Well it's nearly a year later but I figured out that the "One or more vJoy Devices could not be correlated with their DirectInput counterpart" error message was caused by a mismatch between the vJoy DLL version and the currently installed driver. I just made a new release of xboxToVJoy that checks to make sure the driver and DLL versions match, as that is in fact a requirement of vJoy.
