### ISSUE TITLE
Doesn't support Windows 10, installable versions of vJoy on Windows 10 is vJoy 2.0.5 and greater

### ISSUE THREAD

**Issue by heyj-ca** [briankendall/xboxToVJoy#2]
Currently vboxToVJoy supports vJoy 2.0.4, which is uninstallable for Windows 10.  Windows 10 has seen fixes in vJoy since version 2.0.5.  I appreciate your effort in making this program, and am curious if updating for a higher vJoy sdk is onerous?

Currently I either cannot install a proper vJoy and have no vJoy devices show up, or install with vJoy devices but currently I get an error related to Issue #1.

**Comment by briankendall** [comment]
Just made [a new release of xboxToVJoy](https://github.com/briankendall/xboxToVJoy/releases/tag/v1.0.2) that has some bug fixes and is updated to use vJoy 2.1.6. Give it a try and let me know if it works for you in Windows 10.

**Comment by heyj-ca** [comment]
Wow I appreciate the quick response.  I tried out your new release and it works!  The only issue is it crashes on launch every so often.  Not a huge issue but sometimes it takes a few launches for it to actually open without crashing.  Thanks!
